{{- if .Values.isGKE }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Namespace }}-allow-namespace-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
{{- end }}
